-- MySQL Script generated by MySQL Workbench
-- 04/27/16 21:53:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SunOnlineDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SunOnlineDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SunOnlineDB` DEFAULT CHARACTER SET utf8 ;
USE `SunOnlineDB` ;

-- -----------------------------------------------------
-- Table `SunOnlineDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_pwd` VARCHAR(45) NOT NULL,
  `user_mobile` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  UNIQUE INDEX `user_mobile_UNIQUE` (`user_mobile` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`old_driver_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`old_driver_video` (
  `LSJ_video_id` INT NOT NULL AUTO_INCREMENT,
  `LSJ_video_name` VARCHAR(45) NOT NULL,
  `LSJ_video_url` VARCHAR(45) NOT NULL,
  `LSJ_video_date` DATE NOT NULL,
  `LSJ_video_pic_url` VARCHAR(45) NOT NULL,
  `LSJ_video_played_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`LSJ_video_id`),
  UNIQUE INDEX `video_id_UNIQUE` (`LSJ_video_id` ASC),
  UNIQUE INDEX `video_name_UNIQUE` (`LSJ_video_name` ASC),
  UNIQUE INDEX `video_url_UNIQUE` (`LSJ_video_url` ASC),
  UNIQUE INDEX `video_pic_url_UNIQUE` (`LSJ_video_pic_url` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`higo_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`higo_video` (
  `HIGO_video_id` INT NOT NULL AUTO_INCREMENT,
  `HIGO_video_name` VARCHAR(45) NOT NULL,
  `HIGO_video_url` VARCHAR(45) NOT NULL,
  `HIGO_video_date` DATE NOT NULL,
  `HIGO_video_pic_url` VARCHAR(45) NOT NULL,
  `HIGO_video_played_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`HIGO_video_id`),
  UNIQUE INDEX `video_id_UNIQUE` (`HIGO_video_id` ASC),
  UNIQUE INDEX `video_name_UNIQUE` (`HIGO_video_name` ASC),
  UNIQUE INDEX `video_url_UNIQUE` (`HIGO_video_url` ASC),
  UNIQUE INDEX `video_pic_url_UNIQUE` (`HIGO_video_pic_url` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`college_voice_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`college_voice_player` (
  `player_id` INT NOT NULL,
  `player_name` VARCHAR(45) NOT NULL,
  `player_gender` TINYINT(1) NOT NULL,
  `player_school` VARCHAR(45) NOT NULL,
  `player_number` INT NOT NULL,
  PRIMARY KEY (`player_id`, `player_number`),
  UNIQUE INDEX `people_id_UNIQUE` (`player_id` ASC),
  UNIQUE INDEX `player_number_UNIQUE` (`player_number` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`college_voice_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`college_voice_video` (
  `ZQY_video_id` INT NOT NULL AUTO_INCREMENT,
  `ZQY_video_name` VARCHAR(45) NOT NULL,
  `ZQY_video_url` VARCHAR(45) NOT NULL,
  `ZQY_video_date` DATE NOT NULL,
  `ZQY_video_pic_url` VARCHAR(45) NOT NULL,
  `ZQY_video_played_number` INT NOT NULL DEFAULT 0,
  `zqy_player_number` INT NOT NULL,
  PRIMARY KEY (`ZQY_video_id`),
  UNIQUE INDEX `video_id_UNIQUE` (`ZQY_video_id` ASC),
  UNIQUE INDEX `video_name_UNIQUE` (`ZQY_video_name` ASC),
  UNIQUE INDEX `video_url_UNIQUE` (`ZQY_video_url` ASC),
  UNIQUE INDEX `video_pic_url_UNIQUE` (`ZQY_video_pic_url` ASC),
  INDEX `fk_zqy_video_zqy_player_idx` (`zqy_player_number` ASC),
  CONSTRAINT `fk_zqy_video_zqy_player`
    FOREIGN KEY (`zqy_player_number`)
    REFERENCES `SunOnlineDB`.`college_voice_player` (`player_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`Administrator` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(45) NOT NULL,
  `admin_pwd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC),
  UNIQUE INDEX `admin_name_UNIQUE` (`admin_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`SX_school_pic_library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`SX_school_pic_library` (
  `pic_lib_id` INT NOT NULL AUTO_INCREMENT,
  `pic_lib_name` VARCHAR(45) NOT NULL,
  `pic_lib_url` VARCHAR(45) NOT NULL,
  `HDpic_lib_url` VARCHAR(45) NOT NULL,
  `pic_lib_type` VARCHAR(45) NOT NULL,
  `pic_lib_uploader` VARCHAR(45) NOT NULL,
  `pic_lib_date` DATE NOT NULL,
  PRIMARY KEY (`pic_lib_id`),
  UNIQUE INDEX `library_pic_id_UNIQUE` (`pic_lib_id` ASC),
  UNIQUE INDEX `library_pic_name_UNIQUE` (`pic_lib_name` ASC),
  UNIQUE INDEX `library_pic_url_UNIQUE` (`pic_lib_url` ASC),
  UNIQUE INDEX `library_HDpic_url_UNIQUE` (`HDpic_lib_url` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `SunOnlineDB`.`college_pinoeer_intro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SunOnlineDB`.`college_pinoeer_intro` (
  `fcl_id` INT NOT NULL AUTO_INCREMENT,
  `fcl_name` VARCHAR(45) NOT NULL,
  `fcl_url` VARCHAR(45) NOT NULL,
  `fcl_date` DATE NOT NULL,
  PRIMARY KEY (`fcl_id`),
  UNIQUE INDEX `fcl_id_UNIQUE` (`fcl_id` ASC),
  UNIQUE INDEX `fcl_name_UNIQUE` (`fcl_name` ASC),
  UNIQUE INDEX `fcl_url_UNIQUE` (`fcl_url` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
